import { addIcons } from 'ionicons';
import {
  add,
  addOutline,
  appsOutline,
  arrowBackOutline,
  basketOutline,
  calendarOutline,
  cartOutline,
  checkmarkCircle,
  todayOutline,
  clipboardOutline,
  checkmarkCircleOutline,
  chevronBackOutline,
  chevronDownOutline,
  chevronUpOutline,
  copyOutline,
  eggOutline,
  eyeOffOutline,
  eyeOutline,
  fishOutline,
  flameOutline,
  flashOutline,
  flaskOutline,
  heartOutline,
  hourglassOutline,
  iceCreamOutline,
  leafOutline,
  lockClosedOutline,
  logOutOutline,
  mailOutline,
  notificationsOutline,
  nutritionOutline,
  paperPlaneOutline,
  peopleOutline,
  personOutline,
  removeOutline,
  restaurantOutline,
  timeOutline,
  waterOutline,
} from 'ionicons/icons';

// Explicitly registers every icon used anywhere in the app instead of relying on
// Ionicons' runtime lazy-loading by name, which has intermittently failed to
// render specific icons (seen both in Karma test runs and in the live app).
export function registerAppIcons(): void {
  addIcons({
    add,
    'add-outline': addOutline,
    'today-outline': todayOutline,
    'clipboard-outline': clipboardOutline,
    'apps-outline': appsOutline,
    'arrow-back-outline': arrowBackOutline,
    'basket-outline': basketOutline,
    'calendar-outline': calendarOutline,
    'cart-outline': cartOutline,
    'checkmark-circle': checkmarkCircle,
    'checkmark-circle-outline': checkmarkCircleOutline,
    'chevron-back-outline': chevronBackOutline,
    'chevron-down-outline': chevronDownOutline,
    'chevron-up-outline': chevronUpOutline,
    'copy-outline': copyOutline,
    'egg-outline': eggOutline,
    'eye-off-outline': eyeOffOutline,
    'eye-outline': eyeOutline,
    'fish-outline': fishOutline,
    'flame-outline': flameOutline,
    'flash-outline': flashOutline,
    'flask-outline': flaskOutline,
    'heart-outline': heartOutline,
    'hourglass-outline': hourglassOutline,
    'ice-cream-outline': iceCreamOutline,
    'leaf-outline': leafOutline,
    'lock-closed-outline': lockClosedOutline,
    'log-out-outline': logOutOutline,
    'mail-outline': mailOutline,
    'notifications-outline': notificationsOutline,
    'nutrition-outline': nutritionOutline,
    'paper-plane-outline': paperPlaneOutline,
    'people-outline': peopleOutline,
    'person-outline': personOutline,
    'remove-outline': removeOutline,
    'restaurant-outline': restaurantOutline,
    'time-outline': timeOutline,
    'water-outline': waterOutline,
  });
}
